openapi: 3.0.3
info:
  title: Choreotest
  description: >-
    This is a sample API specification for a simple reading list application with in-memory cache
    written in Nodejs
paths:
  /:
    get:
      summary: get hello 
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type : object
                properties:
                  message:
                    type: string
                    example: "Hello World"